uniE800 = "的"
uniE801 = "一"
uniE802 = "是"
uniE803 = "了"
uniE804 = "我"
uniE805 = "不"
uniE806 = "人"
uniE807 = "在"
uniE808 = "他"
uniE809 = "有"
uniE80A = "这"
uniE80B = "个"
uniE80C = "上"
uniE80D = "们"
uniE80E = "来"
uniE80F = "到"
uniE810 = "时"
uniE811 = "大"
uniE812 = "地"
uniE813 = "为"
uniE814 = "子"
uniE815 = "中"
uniE816 = "你"
uniE817 = "说"
uniE818 = "生"
uniE819 = "国"
uniE81A = "年"
uniE81B = "着"
uniE81C = "就"
uniE81D = "那"
uniE81E = "和"
uniE81F = "要"
uniE820 = "她"
uniE821 = "出"
uniE822 = "也"
uniE823 = "得"
uniE824 = "里"
uniE825 = "后"
uniE826 = "自"
uniE827 = "以"
uniE828 = "会"
uniE829 = "家"
uniE82A = "可"
uniE82B = "下"
uniE82C = "而"
uniE82D = "过"
uniE82E = "天"
uniE82F = "去"
uniE830 = "能"
uniE831 = "对"
uniE832 = "小"
uniE833 = "多"
uniE834 = "然"
uniE835 = "于"
uniE836 = "心"
uniE837 = "学"
uniE838 = "么"
uniE839 = "之"
uniE83A = "都"
uniE83B = "好"
uniE83C = "看"
uniE83D = "起"
uniE83E = "发"
uniE83F = "当"
uniE840 = "没"
uniE841 = "成"
uniE842 = "只"
uniE843 = "如"
uniE844 = "事"
uniE845 = "把"
uniE846 = "还"
uniE847 = "用"
uniE848 = "第"
uniE849 = "样"
uniE84A = "道"
uniE84B = "想"
uniE84C = "作"
uniE84D = "种"
uniE84E = "开"
uniE84F = "美"
uniE850 = "乳"
uniE851 = "阴"
uniE852 = "液"
uniE853 = "茎"
uniE854 = "欲"
uniE855 = "呻"
uniE856 = "肉"
uniE857 = "交"
uniE858 = "性"
uniE859 = "胸"
uniE85A = "私"
uniE85B = "穴"
uniE85C = "淫"
uniE85D = "臀"
uniE85E = "舔"
uniE85F = "射"
uniE860 = "脱"
uniE861 = "裸"
uniE862 = "骚"
uniE863 = "唇"
